include: package:lint/analysis_options.yaml

linter:
  rules:
    omit_local_variable_types: true
    avoid_classes_with_only_static_members: false
    prefer_single_quotes: true
    file_names: false

    # only for debug
    avoid_print: false

